name: CI

on:
  push:
    branches: [ security-demonstration ]
  pull_requests:
    branches: [ security-demonstration ]

  workflow_dispatch:

  jobs:
    sast:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Bandit Security Scan
          uses: libertyy/py3-bandit-check@v2

        - name: Security Scan Report
          uses: actions/upload-artifact@v2
          with:
            name: Security Report
            path: ${{ RUNNER.temp }}/_github_home/bandit_report.out
