name: Security

on:
  push:
    branches: [ security-demonstration ]
  pull_request:
    branches: [ security-demonstration ]

  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bandit Security Scan
        uses: libertyy/py3-bandit-check@v2

      - name: Security Scan Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: ${{ RUNNER.temp }}/_github_home/bandit_report.out
          
  
  third-party:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
      
      - name: 3rd Party Inventory
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: ./bom.xml


  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Unit Test with pytest
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          cd tests
          pytest --junit-xml=unit-test.xml
          ls -la
